export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'ACCOUNT_EXISTS'
  | 'INVALID_CREDENTIALS'
  | 'UNAUTHENTICATED'
  | 'USERNAME_TAKEN'
  | 'USER_NOT_FOUND'
  | 'REQUEST_NOT_FOUND'
  | 'UNAUTHORIZED'
  | 'FRIEND_REQUEST_CONFLICT'
  | 'HAND_IN_PROGRESS'
  | 'ILLEGAL_ACTION'
  | 'ROOM_NOT_FOUND'
  | 'ROOM_FULL'
  | 'ROOM_STARTED'
  | 'ROOM_CLOSED'
  | 'NOT_ROOM_HOST'
  | 'NOT_ROOM_MEMBER'
  | 'ACTIVE_ROOM_EXISTS'
  | 'ALREADY_ROOM_MEMBER'
  | 'INVITATION_NOT_FOUND'
  | 'INVITATION_EXISTS'
  | 'NOT_INVITATION_RECIPIENT'
  | 'MUST_BE_FRIEND'
  | 'NOT_ENOUGH_PLAYERS'
  | 'MEMBERS_NOT_READY'
  | 'ROOM_ACCESS_DENIED'
  | 'TABLE_NOT_FOUND'
  | 'TABLE_CLOSED'
  | 'HAND_NOT_FOUND'
  | 'STALE_GAME_STATE'
  | 'NOT_YOUR_TURN'
  | 'DUPLICATE_ACTION'
  | 'TRAINING_NOT_FOUND'
  | 'TRAINING_ACCESS_DENIED'
  | 'TRAINING_CLOSED'
  | 'TRAINING_PARTICIPANT_LEFT'
  | 'TRAINING_DECISION_NOT_FOUND'
  | 'TRAINING_FEEDBACK_UNAVAILABLE'
  | 'TRAINING_SESSION_NOT_FOUND'
  | 'TRAINING_ACCESS_DENIED'
  | 'SCENARIO_NOT_FOUND'
  | 'ILLEGAL_TRAINING_ACTION'
  | 'DUPLICATE_TRAINING_DECISION'
  | 'STRATEGY_UNAVAILABLE'
  | 'INVALID_CARD_STATE'
  | 'INVALID_RANGE'
  | 'EMPTY_RANGE'
  | 'UNSUPPORTED_CALCULATION_METHOD'
  | 'STRATEGY_VERSION_NOT_FOUND'
  | 'NO_COMPATIBLE_STRATEGY_ROW'
  | 'EVALUATION_CONTEXT_INVALID'
  | 'POSTFLOP_STREET_REQUIRED'
  | 'POSTFLOP_TERMINAL'
  | 'POSTFLOP_STALE_SCENARIO'
  | 'POSTFLOP_INVALID_BOARD'
  | 'POSTFLOP_EVALUATION_UNAVAILABLE'
  | 'HAND_HISTORY_NOT_FOUND'
  | 'HAND_HISTORY_NOT_TERMINAL'
  | 'HAND_HISTORY_REPLAY_UNAVAILABLE'
  | 'ANALYTICS_UNAVAILABLE'
  | 'HAND_HISTORY_RETENTION_REQUIRED'
  | 'RECONNECT_REQUIRED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'VALIDATION_FAILED'
  | 'DRAFT_CONFLICT'
  | 'INVALID_STATE_TRANSITION'
  | 'ACTIVE_VERSION_CONFLICT'
  | 'RETIRE_REASON_REQUIRED'
  | 'INVALID_INPUT'
  | 'INTERNAL_ERROR';

export class ApiError extends Error {
  readonly status: number;
  readonly code: ErrorCode;

  constructor(status: number, code: ErrorCode, message: string) {
    super(message);
    this.status = status;
    this.code = code;
  }
}

// Shape mandated by contracts/auth-api.md: { error: { code, message } }.
export function errorBody(code: ErrorCode, message: string) {
  return { error: { code, message } };
}
